# Generated by Django 3.1.5 on 2021-05-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
