# Generated by Django 3.1.5 on 2021-05-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_by_moderator',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
