# Generated by Django 3.1.5 on 2021-05-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210501_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='completed_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='deadline_time',
        ),
    ]
