# Generated by Django 3.1.5 on 2021-05-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210501_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_by_moderator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_by_moderator', models.TextField(null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.task')),
            ],
        ),
    ]
