# Generated by Django 3.1.5 on 2021-05-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210501_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Completed',
            new_name='CompletedTask',
        ),
    ]
