# Generated by Django 3.1.5 on 2021-05-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_moderator'),
        ('todo', '0006_auto_20210501_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.moderator'),
        ),
    ]
