# Generated by Django 3.1.5 on 2021-05-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_task_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtask',
            old_name='task',
            new_name='task_id',
        ),
    ]
