# Generated by Django 3.1.5 on 2021-05-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20210501_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='moderator',
            old_name='name',
            new_name='username',
        ),
    ]
